### ISSUE TITLE
不明的操作

### ISSUE THREAD

**Issue by Droidtown** [joanneyaya/LokiHub#1]
https://github.com/joanneyaya/LokiHub/blob/3a568a9008d1dd48c960d54474551522b19ba5e1/ChiCorrBot/intent/Loki_syntax.py#L110

這兩段 utterance 內都額外呼叫了 Articut，但我看不太懂目的是什麼。

**Comment by joanneyaya** [comment]
原意為把使用者的病句先斷詞，再使用index進行修正，但後來改用args的方式，謝謝！
