### ISSUE TITLE
inputSTR 即可處理

### ISSUE THREAD

**Issue by Droidtown** [joanneyaya/LokiHub#2]
https://github.com/joanneyaya/LokiHub/blob/3a568a9008d1dd48c960d54474551522b19ba5e1/ChiCorrBot/intent/Loki_syntax.py#L143

如果只是要處理句首的「還」-> 「還有」的話，那麼只要這樣做…
```python
textSTR = re.sub("^還(?!有)", "還有", inputSTR)
```
就可以了。
^ 是句首的意思
(?!有) 是「其後不能跟著『有』」的意思。
所以這一段就是說「把一個在句首的『還』字，且其後不是『有』的情況下，將之取代成『還有』」。

**Comment by joanneyaya** [comment]
好的，學到re.sub的方式，謝謝！
