### ISSUE TITLE
讓使用者的輸入「正規化」，而不是讓自己的程式去配合使用者。

### ISSUE THREAD

**Issue by Droidtown** [joanneyaya/LokiHub#3]
https://github.com/joanneyaya/LokiHub/blob/8e5ef58203b3ae31cc588c13c2f596fb1892ac3d/ChiCorrBot/intent/Loki_semantics.py#L49

`if ans == "Y" or ans == "y":`
這是讓程式去配合使用者。

我們可以把使用者的輸入「全部變成小寫」，這麼一來，就簡單多了。
`if ans.lower() in ("y", "yes", "yeah", "ok"):`

透過 .lower()，我們就能讓 ans 變成「小寫」的情況，再去做比對。這樣就不用寫一堆 or 了。這就是把使用者的輸入「正規化」(變成一致的格式) 的意思。

**Comment by joanneyaya** [comment]
好的，我會修改，謝謝！
